return {
    "nvim-treesitter/nvim-treesitter",
    build = ":TSUpdate",
    config = function()
        local configs = require("nvim-treesitter.configs")

        configs.setup({
            ensure_installed = {
                "bash",
                "c",
                "c_sharp",
                "cpp",
                "css",
                "scss",
                "csv",
                "diff",
                "dockerfile",
                "editorconfig",
                "git_config",
                "git_rebase",
                "gitattributes",
                "gitcommit",
                "gitignore",
                "lua",
                "luadoc",
                "vim",
                "vimdoc",
                "javascript",
                "html",
                "go",
                "goctl",
                "gomod",
                "gosum",
                "gotmpl",
                "gowork",
                "graphql",
                "html",
                "http",
                "java",
                "javadoc",
                "javascript",
                "jq",
                "jsdoc",
                "json",
                "json5",
                "jsonc",
                "kotlin",
                "latex",
                "make",
                "markdown",
                "markdown_inline",
                "objdump",
                "python",
                "regex",
                "python",
                "sql",
                "ssh_config",
                "swift",
                "templ",
                "terraform",
                "tmux",
                "tsx",
                "typescript",
                "xml",
                "yaml"
            },
            sync_install = false,
            highlight = { enable = true },
            indent = { enable = true },
        })
    end
}
